Server: #服務設定
  RunMode: debug  #Gin模式 debug/release
  HttpPort: 8000  #Http server port
  ReadTimeout: 60 #讀取有效時間
  WriteTimeout: 60  #寫入有效時間
App:  #應用設定
  DefaultPageSize: 10   #預設文章頁數
  MaxPageSize: 100  #頁數最大上限
  LogSavePath: storage/logs #記錄檔路徑
  LogFileName: app  #記錄檔名稱
  LogFileExt: .log  #記錄檔副檔名
Database: #資料庫設定
  DBType: mysql #資料庫種類
  Username: root  #資料庫帳號
  Password: "0966525307"  #資料庫密碼
  Host: 127.0.0.1:3306  #資料庫IP+Port
  DBName: blog  #資料庫名稱
  TablePrefix: blog_  #資料表前綴
  Charset: utf8 #資料庫字元
  ParseTime: True 
  MaxIdleConns: 10  #資料庫閒置數
  MaxOpenConns: 30  #資料庫最大連線數

